import type { CivicReport, Department, VolunteerTask, Campaign, Reward, NotificationItem } from '../types/database';

export const mockDepartments: Department[] = [
  { id: 'dept-1', name: 'Roads & Infrastructure', description: 'Handles pothole repairs, street pavement, and bridge maintenance.', officer_count: 14, created_at: '2026-01-10', updated_at: '2026-01-10' },
  { id: 'dept-2', name: 'Sanitation & Waste', description: 'Public cleanliness, trash removal, and recycling services.', officer_count: 22, created_at: '2026-01-10', updated_at: '2026-01-10' },
  { id: 'dept-3', name: 'Public Safety & Utilities', description: 'Streetlight outages, traffic signal repair, and hazard mitigation.', officer_count: 18, created_at: '2026-01-10', updated_at: '2026-01-10' },
  { id: 'dept-4', name: 'Parks & Recreation', description: 'Park maintenance, tree pruning, and public garden upkeep.', officer_count: 9, created_at: '2026-01-10', updated_at: '2026-01-10' },
];

export const mockCivicReports: CivicReport[] = [
  {
    id: 'rep-101',
    title: 'Hazardous Deep Pothole on 5th Avenue',
    description: 'A severe pothole approximately 8 inches deep near the pedestrian crosswalk causing vehicle wheel damage and cyclist risk.',
    category: 'Roads & Infrastructure',
    status: 'approved',
    priority: 'urgent',
    latitude: 37.7749,
    longitude: -122.4194,
    location_name: '5th Ave & Pine St Corner',
    image_url: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80',
    reporter_id: 'user-01',
    assigned_department_id: 'dept-1',
    karma_awarded: 50,
    ai_analysis: {
      suggested_category: 'Roads & Infrastructure',
      confidence: 0.96,
      severity_rating: 'Urgent',
      summary: 'Deep road cavity in high-traffic crosswalk zone requiring asphalt patching.',
      tags: ['Pothole', 'Crosswalk Hazard', 'Urgent Patch'],
    },
    created_at: '2026-07-28T09:30:00Z',
    updated_at: '2026-07-29T14:20:00Z',
  },
  {
    id: 'rep-102',
    title: 'Broken Solar Streetlight flickering continuously',
    description: 'The solar streetlight unit #L-402 blinks erratically at night, leaving the children park alley completely unlit.',
    category: 'Public Safety & Utilities',
    status: 'in_progress',
    priority: 'high',
    latitude: 37.7735,
    longitude: -122.418,
    location_name: 'Greenwood Community Park',
    image_url: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
    reporter_id: 'user-02',
    assigned_department_id: 'dept-3',
    karma_awarded: 40,
    ai_analysis: {
      suggested_category: 'Public Safety & Utilities',
      confidence: 0.94,
      severity_rating: 'High',
      summary: 'Faulty solar charge controller or LED fixture causing night illumination safety gap.',
      tags: ['Streetlight', 'Solar Utility', 'Park Safety'],
    },
    created_at: '2026-07-29T11:15:00Z',
    updated_at: '2026-07-30T08:00:00Z',
  },
  {
    id: 'rep-103',
    title: 'Illegal Dumping near Central Market Overflow Container',
    description: 'Large commercial cardboard boxes and electronics dumped illegally behind the food stalls, blocking drainage.',
    category: 'Sanitation & Waste',
    status: 'needs_info',
    priority: 'medium',
    latitude: 37.778,
    longitude: -122.422,
    location_name: 'Central Farmers Market Gate B',
    image_url: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80',
    reporter_id: 'user-03',
    assigned_department_id: 'dept-2',
    karma_awarded: 30,
    ai_analysis: {
      suggested_category: 'Sanitation & Waste',
      confidence: 0.91,
      severity_rating: 'Medium',
      summary: 'Bulk illegal waste accumulation requiring Sanitation crew pickup.',
      tags: ['Sanitation', 'Dumpster Overflow', 'Drainage Block'],
    },
    created_at: '2026-07-30T06:45:00Z',
    updated_at: '2026-07-30T07:10:00Z',
  },
];

export const mockVolunteerTasks: VolunteerTask[] = [
  {
    id: 'task-01',
    title: 'Weekend Riverside Cleanup & Plastic Sort',
    description: 'Join local community volunteers to clean up plastics and debris along the riverbank trail. Equipment provided!',
    category: 'Environment',
    location: 'Riverside Park North Entrance',
    required_volunteers: 15,
    signed_up_count: 9,
    karma_reward: 100,
    date_time: '2026-08-02T09:00:00Z',
    status: 'open',
    created_at: '2026-07-25',
  },
  {
    id: 'task-02',
    title: 'Community Garden Urban Planting Drive',
    description: 'Help plant native saplings and organic vegetable beds in the neighborhood community garden.',
    category: 'Parks & Greenery',
    location: 'Maple Wood Community Garden',
    required_volunteers: 10,
    signed_up_count: 7,
    karma_reward: 75,
    date_time: '2026-08-05T10:00:00Z',
    status: 'open',
    created_at: '2026-07-26',
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp-01',
    title: 'Solar Lighting for Public Library Courtyard',
    description: 'Fund installation of 12 eco-friendly solar lamp posts to illuminate the public reading lawn at night.',
    partner_name: 'Metro Clean Energy Foundation',
    target_amount: 5000,
    current_amount: 3420,
    category: 'Sustainability',
    status: 'active',
    image_url: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
    created_at: '2026-07-15',
  },
  {
    id: 'camp-02',
    title: 'Youth Civic Tech Workshop & Equipment Fund',
    description: 'Providing laptops and STEM kits for underprivileged students engaging in civic coding and mapping projects.',
    partner_name: 'TechForGood Alliance',
    target_amount: 8000,
    current_amount: 6150,
    category: 'Education',
    status: 'active',
    image_url: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80',
    created_at: '2026-07-20',
  },
];

export const mockRewards: Reward[] = [
  {
    id: 'rew-01',
    title: 'Free Artisanal Coffee & Bakery Treat',
    description: 'Redeem 150 Karma points for any medium coffee and fresh pastry at participating local cafes.',
    partner_name: 'Bean & Bloom Cafe Network',
    karma_cost: 150,
    discount_code: 'KINDRA-BEAN-2026',
    total_available: 50,
    remaining: 32,
    image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
    created_at: '2026-07-01',
    category_id: null,
    partner_id: null,
    updated_at: '2026-07-01',
  },
  {
    id: 'rew-02',
    title: '20% Off City Transit Monthly Pass',
    description: 'Apply 200 Karma points to get 20% discount on metro and public bus monthly commuter passes.',
    partner_name: 'Municipal Transit Authority',
    karma_cost: 200,
    discount_code: 'TRANSIT-CIVIC-20',
    total_available: 100,
    remaining: 68,
    image_url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80',
    created_at: '2026-07-05',
    category_id: null,
    partner_id: null,
    updated_at: '2026-07-05',
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif-01',
    user_id: 'user-01',
    title: 'Report Status Updated',
    message: 'Your report "Hazardous Deep Pothole on 5th Avenue" was verified and dispatched to Roads & Infrastructure.',
    type: 'success',
    is_read: false,
    created_at: '2026-07-29T14:20:00Z',
  },
  {
    id: 'notif-02',
    user_id: 'user-01',
    title: '+50 Karma Points Awarded!',
    message: 'You earned 50 Karma points for your verified civic report. Keep building community impact!',
    type: 'info',
    is_read: false,
    created_at: '2026-07-29T14:21:00Z',
  },
];
