/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#003d9b",
        "primary-container": "#0052cc",
        "on-primary": "#ffffff",
        "on-primary-container": "#c4d2ff",
        "inverse-primary": "#b2c5ff",
        "primary-fixed": "#dae2ff",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-fixed": "#001848",
        "on-primary-fixed-variant": "#0040a2",

        secondary: "#006e2a",
        "secondary-container": "#5cfd80",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00732c",
        "secondary-fixed": "#69ff87",
        "secondary-fixed-dim": "#3ce36a",
        "on-secondary-fixed": "#002108",
        "on-secondary-fixed-variant": "#00531e",

        tertiary: "#5e3c00",
        "tertiary-container": "#7d5200",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffca81",
        "tertiary-fixed": "#ffddb3",
        "tertiary-fixed-dim": "#ffb950",
        "on-tertiary-fixed": "#291800",
        "on-tertiary-fixed-variant": "#624000",

        background: "#f8f9fb",
        "on-background": "#191c1e",
        surface: "#f8f9fb",
        "on-surface": "#191c1e",
        "on-surface-variant": "#434654",
        "surface-bright": "#f8f9fb",
        "surface-dim": "#d9dadc",
        "surface-tint": "#0c56d0",
        "surface-variant": "#e1e2e4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f6",
        "surface-container": "#edeef0",
        "surface-container-high": "#e7e8ea",
        "surface-container-highest": "#e1e2e4",

        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f3",

        outline: "#737685",
        "outline-variant": "#c3c6d6",

        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        base: "8px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
